// ReSharper disable InvertIf
namespace Atc.Analyzer.Rules.Style;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class GlobalUsingsCommonAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor Rule = new(
        RuleIdentifierConstants.Style.GlobalUsingsCommon,
        title: "Use global usings for common namespaces",
        messageFormat: "Using directive '{0}' should be moved to GlobalUsings.cs",
        RuleCategoryConstants.Style,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Using directives for System, Microsoft, and Atc namespaces should be defined as global usings in GlobalUsings.cs for consistency.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Style.GlobalUsingsCommon));

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

    public override void Initialize(AnalysisContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSyntaxNodeAction(AnalyzeUsingDirective, SyntaxKind.UsingDirective);
    }

    private static void AnalyzeUsingDirective(SyntaxNodeAnalysisContext context)
    {
        if (context.Node.SyntaxTree.IsAutoGeneratedFile())
        {
            return;
        }

        var usingDirective = (UsingDirectiveSyntax)context.Node;

        // Skip if this is GlobalUsings.cs
        var fileName = Path.GetFileName(context.Node.SyntaxTree.FilePath);
        if (fileName.Equals("GlobalUsings.cs", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        // Skip if this is a global using (already in the correct place)
        if (usingDirective.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword))
        {
            return;
        }

        // Skip if this is a static using or alias
        if (usingDirective.StaticKeyword.IsKind(SyntaxKind.StaticKeyword) ||
            usingDirective.Alias is not null)
        {
            return;
        }

        // Get the namespace name
        var namespaceName = usingDirective.Name?.ToString();
        if (string.IsNullOrEmpty(namespaceName))
        {
            return;
        }

        // Check if this is a System, Microsoft, or Atc namespace
        if (ShouldBeGlobalUsing(namespaceName!))
        {
            var diagnostic = Diagnostic.Create(
                Rule,
                usingDirective.GetLocation(),
                namespaceName);

            context.ReportDiagnostic(diagnostic);
        }
    }

    private static bool ShouldBeGlobalUsing(string namespaceName)
    {
        return namespaceName.StartsWith("System", StringComparison.Ordinal) ||
               namespaceName.StartsWith("Microsoft", StringComparison.Ordinal) ||
               namespaceName.StartsWith("Atc", StringComparison.Ordinal);
    }
}