namespace Atc.Analyzer.Tests.Rules.Style;

#pragma warning disable SA1135 // Using directives must be qualified
using AnalyzerVerifier = CSharpAnalyzerVerifier<GlobalUsingsCommonAnalyzer>;
#pragma warning restore SA1135 // Using directives must be qualified

[SuppressMessage("", "AsyncFixer01:The method does not need to use async/await", Justification = "OK - Test code")]
[SuppressMessage("", "SA1135::The method does not need to use async/await", Justification = "OK - Test code")]
[SuppressMessage("Naming", "MA0048:File name must match type name", Justification = "OK - Partial class")]
public sealed partial class GlobalUsingsCommonAnalyzerTests
{
    [Fact]
    public async Task NoDiagnostic_ThirdPartyNamespace()
    {
        const string code = """
                            using ThirdParty.Library;

                            public class Sample
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_CustomNamespace()
    {
        const string code = """
                            using MyCompany.MyProject;

                            public class Sample
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_StaticUsingSystem()
    {
        const string code = """
                            using static System.Console;

                            public class Sample
                            {
                                public static void Print() => WriteLine("Hello");
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_UsingAlias()
    {
        const string code = """
                            using SysConsole = System.Console;

                            public class Sample
                            {
                                public static void Print() => SysConsole.WriteLine("Hello");
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_GlobalUsingAlreadyDefined()
    {
        const string code = """
                            global using System;

                            public class Sample
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_NoUsingStatements()
    {
        const string code = """
                            public class Sample
                            {
                                public static string GetData() => "Sample Data";
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_GeneratedCodeClass()
    {
        const string code = """
                            using System;
                            using System.CodeDom.Compiler;

                            [GeneratedCode("MyGen", "1.0.1")]
                            public class GeneratedSample
                            {
                                public static void DoSomething()
                                {
                                }
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_AutoGeneratedHeader()
    {
        const string code = """
                            //------------------------------------------------------------------------------
                            // This code was auto-generated by Generator 1.0.
                            //------------------------------------------------------------------------------
                            using System;

                            public class GeneratedClass
                            {
                                public static void DoSomething()
                                {
                                }
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_MixedThirdPartyAndCustomNamespaces()
    {
        const string code = """
                            using Xunit;
                            using FluentAssertions;
                            using MyCompany.Utilities;

                            public class Sample
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_UsingAliasForDomainConstants()
    {
        const string code = """
                            using Constants = Domain.Constants;

                            public class Sample
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }
}