//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.686.58219.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Atc.Analyzer.Sample.Atc201and202.Scenarios;

/// <summary>
/// Demonstrates that files with auto-generated headers are skipped by ATC201.
/// All methods in this file would normally violate ATC201 (parameter on new line when line is short),
/// but the analyzer skips files with "auto-generated" in the header.
/// </summary>
public class AutoGeneratedHeaderSingleParameterExamples
{
    // This would normally violate ATC201, but is skipped
    public void ShortMethod(
        int x)
    {
    }

    // This would normally violate ATC201, but is skipped
    public void MethodWithSingleParameter(
        string name)
    {
    }

    // This would normally violate ATC201, but is skipped
    public void AnotherMethod(
        bool flag)
    {
    }

    // This would normally violate ATC201, but is skipped
    public void MethodWithNullableParameter(
        int? value)
    {
    }
}