//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.686.58219.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Atc.Analyzer.Sample.Atc201and202.Scenarios;

/// <summary>
/// Demonstrates that files with auto-generated headers are skipped by ATC202.
/// All methods in this file would normally violate ATC202 (multiple parameters on same line),
/// but the analyzer skips files with "auto-generated" in the header.
/// </summary>
public class AutoGeneratedHeaderMultipleParameterExamples
{
    // This would normally violate ATC202, but is skipped
    public void MethodWithTwoParameters(int x, string y)
    {
    }

    // This would normally violate ATC202, but is skipped
    public void MethodWithThreeParameters(int x, string y, bool z)
    {
    }

    // This would normally violate ATC202, but is skipped
    public void MethodWithMixedTypes(int id, string name, IEnumerable<int> items, bool isActive)
    {
    }

    // This would normally violate ATC202, but is skipped
    public static void StaticMethodWithMultipleParams(int x, int y)
    {
    }

    // This would normally violate ATC202, but is skipped
    public async Task AsyncMethodWithMultipleParams(int id, string name)
    {
        await Task.CompletedTask;
    }
}