namespace Atc.Analyzer.Tests.Extensions;

public sealed class SyntaxTreeExtensionsTests
{
    [Fact]
    public void IsAutoGeneratedFile_WithNullSyntaxTree_ReturnsFalse()
    {
        // Arrange
        SyntaxTree? syntaxTree = null;

        // Act
        var result = syntaxTree!.IsAutoGeneratedFile();

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithNoComments_ReturnsFalse()
    {
        // Arrange
        const string code = """
                            namespace MyNamespace;

                            public class MyClass
                            {
                                public void MyMethod()
                                {
                                }
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithNonAutoGeneratedComment_ReturnsFalse()
    {
        // Arrange
        const string code = """
                            // This is a regular comment
                            // Nothing special here
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutoGeneratedInSingleLineComment_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            // This code was auto-generated by a tool
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutoGeneratedUpperCase_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            // This code was AUTO-GENERATED by a tool
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutoGeneratedMixedCase_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            // This code was AuTo-GeNeRaTeD by a tool
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutoGeneratedInMultiLineComment_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            /*
                             * This code was auto-generated
                             * Do not modify manually
                             */
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithStandardAutoGeneratedHeader_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            //------------------------------------------------------------------------------
                            // This code was auto-generated by ApiGenerator 2.0.686.58219.
                            //
                            // Changes to this file may cause incorrect behavior and will be lost if
                            // the code is regenerated.
                            //------------------------------------------------------------------------------
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutogeneratedNoHyphen_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            // This code was autogenerated by a tool
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutoGeneratedInMiddleOfHeader_ReturnsTrue()
    {
        // Arrange
        const string code = """
                            // Copyright 2024
                            // This file is auto-generated
                            // All rights reserved
                            namespace MyNamespace;

                            public class MyClass
                            {
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsAutoGeneratedFile_WithAutoGeneratedNotInLeadingTrivia_ReturnsFalse()
    {
        // Arrange
        const string code = """
                            namespace MyNamespace;

                            public class MyClass
                            {
                                // This method was auto-generated
                                public void MyMethod()
                                {
                                }
                            }
                            """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.IsAutoGeneratedFile();

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void GetEndOfLineTrivia_WithNullSyntaxTree_ReturnsLineFeed()
    {
        // Arrange
        SyntaxTree? syntaxTree = null;

        // Act
        var result = syntaxTree!.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxFactory.LineFeed, result);
    }

    [Fact]
    public void GetEndOfLineTrivia_WithUnixLineEndings_ReturnsLineFeed()
    {
        // Arrange
        const string code = "namespace MyNamespace;\n\npublic class MyClass\n{\n}\n";
        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxKind.EndOfLineTrivia, result.Kind());
        Assert.Equal("\n", result.ToString());
    }

    [Fact]
    public void GetEndOfLineTrivia_WithWindowsLineEndings_ReturnsCarriageReturnLineFeed()
    {
        // Arrange
        const string code = "namespace MyNamespace;\r\n\r\npublic class MyClass\r\n{\r\n}\r\n";
        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxKind.EndOfLineTrivia, result.Kind());
        Assert.Equal("\r\n", result.ToString());
    }

    [Fact]
    public void GetEndOfLineTrivia_WithNoLineEndings_ReturnsLineFeed()
    {
        // Arrange
        const string code = "namespace MyNamespace;";
        var syntaxTree = CSharpSyntaxTree.ParseText(code);

        // Act
        var result = syntaxTree.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxFactory.LineFeed, result);
    }

    [Fact]
    public void GetEndOfLineTrivia_OnNode_WithNullNode_ReturnsLineFeed()
    {
        // Arrange
        SyntaxNode? node = null;

        // Act
        var result = node!.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxFactory.LineFeed, result);
    }

    [Fact]
    public void GetEndOfLineTrivia_OnNode_WithUnixLineEndings_ReturnsLineFeed()
    {
        // Arrange
        const string code = "namespace MyNamespace;\n\npublic class MyClass\n{\n    public void MyMethod() { }\n}\n";
        var syntaxTree = CSharpSyntaxTree.ParseText(code);
        var root = syntaxTree.GetRoot();
        var methodNode = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = methodNode.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxKind.EndOfLineTrivia, result.Kind());
        Assert.Equal("\n", result.ToString());
    }

    [Fact]
    public void GetEndOfLineTrivia_OnNode_WithWindowsLineEndings_ReturnsCarriageReturnLineFeed()
    {
        // Arrange
        const string code = "namespace MyNamespace;\r\n\r\npublic class MyClass\r\n{\r\n    public void MyMethod() { }\r\n}\r\n";
        var syntaxTree = CSharpSyntaxTree.ParseText(code);
        var root = syntaxTree.GetRoot();
        var methodNode = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = methodNode.GetEndOfLineTrivia();

        // Assert
        Assert.Equal(SyntaxKind.EndOfLineTrivia, result.Kind());
        Assert.Equal("\r\n", result.ToString());
    }
}