// ReSharper disable ForeachCanBeConvertedToQueryUsingAnotherGetEnumerator
namespace Atc.Analyzer.Extensions;

/// <summary>
/// Extension methods for <see cref="SyntaxTree"/>.
/// </summary>
public static class SyntaxTreeExtensions
{
    /// <summary>
    /// Determines whether the syntax tree represents an auto-generated file.
    /// </summary>
    /// <param name="syntaxTree">The syntax tree to check.</param>
    /// <returns>
    /// <c>true</c> if the file contains "auto-generated" or "autogenerated" in its leading comments (case-insensitive);
    /// otherwise, <c>false</c>.
    /// </returns>
    /// <remarks>
    /// This method checks both single-line and multi-line comments at the beginning of the file
    /// for the presence of "auto-generated" or "autogenerated" text. This is commonly used to identify files
    /// generated by code generators such as T4 templates, API generators, etc.
    /// </remarks>
    public static bool IsAutoGeneratedFile(this SyntaxTree syntaxTree)
    {
        if (syntaxTree is null)
        {
            return false;
        }

        var root = syntaxTree.GetRoot();
        var leadingTrivia = root.GetLeadingTrivia();

        foreach (var trivia in leadingTrivia)
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) &&
                !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                continue;
            }

            var commentText = trivia.ToString();
            if (commentText.IndexOf("auto-generated", StringComparison.OrdinalIgnoreCase) >= 0 ||
                commentText.IndexOf("autogenerated", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return true;
            }
        }

        return false;
    }
}